package ru.rc.shml;

import java.util.List;

import org.objectweb.asm.ClassReader;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.InsnList;
import org.objectweb.asm.tree.InsnNode;
import org.objectweb.asm.tree.IntInsnNode;
import org.objectweb.asm.tree.MethodNode;

public class PatchHardcoded 
{
	
	@SuppressWarnings("unchecked")
	static public byte[] walk(String classname,byte[] classbytes)
	{
		
		//this injection remove significant penalty on loot
		//expect completely different game balance
		//as you will literally swim in money after very first boarded pirate
		if (classname.equalsIgnoreCase("fi.bugbyte.spacehaven.world.Ship"))
		{
			System.out.println("fi.bugbyte.spacehaven.world.Ship");
			
			ClassReader reader = new ClassReader(classbytes);
			ClassNode node = new ClassNode();
			reader.accept(node,0);
			
			for (MethodNode mv : (List<MethodNode>)node.methods)
			{
				if (mv.name.equals("reduceStorageItemsOnSeize"))
				{
					System.out.println("reduceStorageItemsOnSeize");
					System.out.println("no loot reduction mod applied");
					
					//placeholder for patch files
					//table will be generated by "difficator"
					mv.instructions = new InsnList();
					mv.instructions.add(new InsnNode(Opcodes.RETURN));
					break;
				}
			}
		    ClassWriter writer = new ClassWriter(3);
		    node.accept(writer);
		    return writer.toByteArray();
		}

		if (classname.equalsIgnoreCase("fi.bugbyte.spacehaven.world.ShipHelper$SystemPointManager"))
		{
			System.out.println("fi.bugbyte.spacehaven.world.ShipHelper$SystemPointManager");
			
			ClassReader reader = new ClassReader(classbytes);
			ClassNode node = new ClassNode();
			reader.accept(node,0);
			
			for (MethodNode mv : (List<MethodNode>)node.methods)
			{
				if (mv.name.equals("getShipPoints"))
				{
					System.out.println("getShipPoints");
					System.out.println("512 system points for all ships applied");
					
					//placeholder for patch files
					//table will be generated by "difficator"
					mv.instructions = new InsnList();
					mv.instructions.add(new IntInsnNode(Opcodes.SIPUSH,128));//will be multiplied by 4 later
					mv.instructions.add(new InsnNode(Opcodes.IRETURN));
					break;
				}
			}
		    ClassWriter writer = new ClassWriter(3);
		    node.accept(writer);
		    return writer.toByteArray();
		}
		
		//if (classname.contains("SystemPointManager"))
			//System.out.println(classname);
		
		return classbytes;
	}

}
